[package]
name = "{{ project_name }}"
version = "0.1.0"
edition = "2021"

[dependencies]
#tracing
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.17", features = ["json"] }

#lambda runtime
lambda_runtime = "0.8.1"
serde_json = "1.0.108"
tokio = { version = "1", features = ["macros"] }
